### PR TITLE
[WIP] feat: adding draft of predict function

### PR DESCRIPTION
**Pull request by kjappelbaum**
Still need to think about the following things 

- [ ] Do we want to take a filename or filedata
- [ ] Probably should introduce a small wrapper to align our anode names with the ones of `xrd-calculate`

### CODE REVIEW

**Comment by lpatiny** [comment]
xrd-calculate is not written in javascript and can therefore not be compiled for the browser that it a requirement for this library.
I don't know if you could translate the library to javascript or try to create a webassembly project.

**Comment by kjappelbaum** [comment]
Thanks for the feedback, but I do not fully understand your comment. `xrd-calculate` already comes with a wasm binary which is why i went forward using it. Did you try to compile it for the browser and it didn't work?

**Comment by lpatiny** [comment]
We can compile the library. `predict` is not being exported so is not in the final code but you could try `npm run build` after importing it and execute the resulting library in a browser.

So the goal here is no generate a xrd from a cif right ? Where is the cif coming from ? You want to drag / drop a cif in the webpage ?  Or reuse a previously imported file ?

I think prediction is not directly related to xrd-analysis project. I would create a new project like xrd-tools for example.

**Comment by kjappelbaum** [comment]
> I think prediction is not directly related to xrd-analysis project. I would create a new project like xrd-tools for example.

The goal would be ideally to use the `cif` that is attached to the sample. Then one could compare the theoretical pattern with the measured one. This would be the main use case. For this reason, and since it only calls on external library, I put it here. But I can also factor it out into a separate project. 

Of course, one could imagine that one wants to have a standalone predict function for any `cif` but having the ability to compare a measured pattern with a theoretical one seems more important.

**Comment by lpatiny** [comment]
I think indeed you could make a project like xrd-tools for this.

Could you try to be sure you can build it for the browser and send directly a 'string' to the code in the browser to get the simulation ?

Loading cif in the view to make the prediction should be possible.

**Comment by kjappelbaum** [comment]
Closing this PR because I'll move the prediction to `xrd-tools`.

**Pull request closed without merging**
